# Generated by Django 6.0 on 2026-08-09 10:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('country', models.CharField(default='India', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
                ('rent', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(100000)])),
                ('floor', models.IntegerField()),
                ('room_state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('uid', models.CharField(max_length=12, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=100, null=True)),
                ('emg_contact', models.CharField(max_length=10)),
                ('move_in_date', models.DateField(auto_now=True)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adv_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.address')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.room')),
            ],
        ),
    ]
