# Generated by Django 6.0 on 2026-08-09 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='type',
        ),
        migrations.AddField(
            model_name='room',
            name='sharing_type',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
