# Generated by Django 6.0 on 2026-08-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_room_type_room_sharing_type_alter_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='emg_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='emg_contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
