# Generated by Django 6.0 on 2026-08-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_room_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='move_in_date',
            field=models.DateField(),
        ),
    ]
