# Generated by Django 6.0 on 2026-08-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_tenant_move_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
