# Generated by Django 6.0 on 2026-08-10 14:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_tenant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
