# Generated by Django 6.0 on 2026-08-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_state',
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='rent',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='room',
            name='sharing_type',
            field=models.CharField(max_length=10),
        ),
    ]
