# Generated by Django 6.0 on 2026-08-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_tenant_emg_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='emg_contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
