# Generated by Django 6.0 on 2026-08-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_tenant_emg_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(default=9999999999, max_length=13),
            preserve_default=False,
        ),
    ]
