# Generated by Django 6.0 on 2026-08-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_tenant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
