# Generated by Django 6.0 on 2026-09-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_room_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
    ]
