# Generated by Django 6.0 on 2026-09-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
