# Generated by Django 6.0 on 2026-09-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_room_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
