# Generated by Django 6.0 on 2026-09-06 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_room_floor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(choices=[(1, 'Floor 1'), (2, 'Floor 2'), (3, 'Floor 3'), (4, 'Floor 4'), (5, 'Floor 5'), (6, 'Floor 6'), (7, 'Floor 7'), (8, 'Floor 8')]),
        ),
        migrations.AlterField(
            model_name='room',
            name='rent',
            field=models.CharField(choices=[('8000', '₹8000'), ('9000', '₹9000'), ('12000', '₹12000'), ('12500', '₹12500')], max_length=100000),
        ),
        migrations.AlterField(
            model_name='room',
            name='sharing_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('quadruple', 'Quadruple')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='gender',
            field=models.CharField(choices=[('', 'Select Gender'), ('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10),
        ),
    ]
