# Generated by Django 6.0 on 2026-09-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='advanced_used',
            new_name='advance_used',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='panalty',
            new_name='penalty',
        ),
    ]
