# Generated by Django 6.0 on 2026-09-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_rename_advanced_used_payment_advance_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='rent_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending'),
        ),
    ]
