# Generated by Django 6.0 on 2026-09-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_tenant_rent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='rent_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending'),
        ),
    ]
