# Generated by Django 6.0 on 2026-09-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_tenant_rent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rent',
            field=models.PositiveIntegerField(choices=[(8000, '₹8000'), (9000, '₹9000'), (12000, '₹12000'), (12500, '₹12500')]),
        ),
    ]
