# Generated by Django 6.0 on 2026-09-14 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_room_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('furniture', 'Furniture'), ('other', 'Other')])),
                ('prioriy', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')])),
                ('issue', models.TextField(max_length=2000)),
                ('complaint_status', models.CharField()),
                ('date', models.DateField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tenant')),
            ],
        ),
    ]
