# Generated by Django 6.0 on 2026-09-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_complaintregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplaintRegistration',
        ),
    ]
