# Generated by Django 6.0 on 2026-09-14 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='status_update_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 14, 18, 56, 1, 913806, tzinfo=datetime.timezone.utc)),
        ),
    ]
