# Generated by Django 6.0 on 2026-09-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_maintenance_status_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status_update_time',
            field=models.DateTimeField(),
        ),
    ]
