# Generated by Django 6.0 on 2026-09-14 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_maintenance_status_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status_update_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 14, 18, 59, 16, 212706, tzinfo=datetime.timezone.utc)),
        ),
    ]
