# Generated by Django 6.0 on 2026-09-15 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_alter_maintenance_status_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='complaint_status',
            field=models.CharField(default='open'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status_update_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 15, 14, 20, 23, 139488, tzinfo=datetime.timezone.utc)),
        ),
    ]
