# Generated by Django 6.0 on 2026-09-15 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_maintenance_complaint_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('wifi', 'Wifi'), ('electrical', 'Electrical'), ('furniture', 'Furniture'), ('other', 'Other')], default='plumbing'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='complaint_status',
            field=models.CharField(choices=[('open', 'Open'), ('inprogress', 'Inprogress'), ('resolved', 'Resolved')], default='open'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='prioriy',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status_update_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 15, 14, 33, 13, 520046, tzinfo=datetime.timezone.utc)),
        ),
    ]
