# Generated by Django 6.0 on 2026-09-15 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alter_maintenance_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='prioriy',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status_update_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 15, 14, 38, 17, 708456, tzinfo=datetime.timezone.utc)),
        ),
    ]
