# Generated by Django 6.0 on 2026-09-15 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_remove_maintenance_prioriy_maintenance_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
