# Generated by Django 6.0 on 2026-09-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_alter_maintenance_status_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='issue',
            field=models.TextField(),
        ),
    ]
