# Generated by Django 6.0 on 2026-09-17 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_alter_maintenance_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
