# Generated by Django 6.0 on 2026-09-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_alter_maintenance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
