# Generated by Django 6.0 on 2026-09-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_tenant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='rent_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('paid', 'Paid')], default='pending'),
        ),
    ]
