# Generated by Django 6.0 on 2026-09-21 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_tenant_rent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
